print('=======================')
print('Nama : Muh Bintang Mahardani')
print("Kelas: 17.1A.26")
print("Alamat : Jalan asia baru")
print("Asal Sekolah : SMK TRI ARGA 2")
print('Nama pengguna : dani_1245')
print('aku dan kamu')